#node test
dag_node() %>% dag_diagrammer() %>%
  DiagrammeR::render_graph()
dag_create() %>% dag_node() %>% dag_diagrammer() %>%
  DiagrammeR::render_graph()

dag_create() %>% dag_node("test", rhs = normal) %>% dag_diagrammer() %>%
  DiagrammeR::render_graph()

dag_create() %>% dag_node(data = attitude$complaints) %>% dag_diagrammer() %>%
  DiagrammeR::render_graph()

dag_create() %>% dag_node(c("Momma","Poppa"),data = attitude$complaints, rhs = normal(0,10)) %>% dag_diagrammer() %>%
  DiagrammeR::render_graph()

dag_create() %>% dag_node(rhs = normal(0,10), data = attitude[, 2:7]) %>% dag_diagrammer() %>%
  DiagrammeR::render_graph()

dag_create() %>%
  dag_node("response") %>%
  dag_node(label = c("a","b"),
           rhs = alpha+beta*x,
           data = attitude[, 2:7]) %>%
  dag_edge(from = c("attitude$raises","complaints"),
           to = "response") %>%
  dag_diagrammer() %>%
  DiagrammeR::render_graph()

dag_create() %>% dag_node(data = attitude[, 2:7]) %>% dag_diagrammer() %>%
  DiagrammeR::render_graph()

dag_create() %>%
  dag_node(c("comp","priv","learn","rais","crit","adv"),
           data = attitude[, 2:7],
           rhs = normal(0,10))

dag_create() %>%
  dag_node("Sales Price","Y",
           rhs = normal(mean,SD),
           obs = TRUE,
           data = attitude$rating) %>%
  dag_diagrammer() %>% DiagrammeR::render_graph()


graph = dag_create() %>%
  dag_node(label = "y",descr = "Sales Price",
           rhs = normal,
           data = houseDF$SalePrice) %>%
  dag_node(label = "mean",descr = "Exp Sales Price",
           child = "Sales Price",
           rhs = alpha + beta * x) %>%
  dag_node(label = "x",descr = "Square Footage",
           data = houseDF$`1stFlrSF`,
           child = "mean") %>%
  dag_node(label = "beta", descr = "Price per Sq Foot",
           child = "mean", rhs = normal(0,10000)) %>%
  dag_node(label = "SD", descr = "Std Dev of Sales Price",
           child = "Sales Price", rhs = lognormal(0,100)) %>%
  dag_node(label = "alpha", descr = "Intercept",
           child = "mean", rhs = normal(160000,10000)) %>%
  dag_plate("Observation","i",
            nodeLabels = c("y","x","mean")) %>%
  dag_plate("Zip Code","j",
            nodeLabels = "alpha",
            dataNode = houseDF$Neighborhood) %>%
  dag_render()
###UNFIN:: generate zip code node automatically with data from dag_plate()
###function ... any formula children should have extraction added to
###formula... add zip node..add edge from zip to plated nodes child
###only add zip to plated nodes child if child outside of plate

## below line should be generated by plate being given a data node
#dag_node(label = "zip",descr = "Zip Code",
#         child = "mean", data = houseDF$Neighborhood) %>%

graph = dag_create() %>%
  dag_node("Rating","y",
           data = attitude$rating,
           rhs = normal(mu,sd)) %>%
  dag_node("Exp Rating","mu",
           rhs = int + coef * x,
           child = "rating") %>%
  dag_node("Intercept","int",
           rhs = normal(0,10),
           child = "mu") %>%
  dag_node("Coefficient","coef",
           rhs = normal(0,10),
           child = "mu") %>%
  dag_node("Std. Dev.","sd",
           rhs = cauchy(0,3,truncation = c(0,Inf)),
           child = "rating") %>%
  dag_node("Complaints","x",
           data = attitude$complaints,
           child = "mu") %>%
  dag_plate("Observation","i",
            nodeLabels = c("x","mu","y")) %>%
  dag_plate("Predictors","j",
            nodeLabels = c("x","int","coef")) %>%
  dag_render()



descr = "X"
label = as.character(NA)
data = NULL # vector or df
rhs = NULL ##not vectorized
child = as.character(NA) ##not vectorized
obs = FALSE
